[project]
name = "fb-clipsync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "librosa>=0.11.0",
    "moviepy==1.0.3",
    "numpy>=2.2.4",
    "opencv-python>=4.11.0.86",
    "scenedetect[opencv]>=0.6.6",
]
